### ISSUE TITLE
having problems connecting more than one client

### ISSUE THREAD

**Issue by apc300** [YoFuzzy3/CommandSync#1]
i have 8 servers and a bungee
i followed your instructions
one server registers, as shown in the bungee console
the rest of them spam the fail message

what do i do? i have double-checked the configs 5 times
thanks!

the host was giving them separate ip's, issue is sorted, 
please add more debugging messages in the future so its possible to see which environment variables match up

**Comment by YoFuzzy3** [comment]
Debugging messages for what variables that show up when exactly?
